# Generated by Django 3.1.4 on 2020-12-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='desc_hospital',
            field=models.TextField(null=True),
        ),
    ]
